package org.immunizationsoftware.dqa.tester.profile;

public enum ProfileField {
  FHS("FHS", ProfileFieldType.SEGMENT, "FHS", "File Header Segment", null),
  FTS("FTS", ProfileFieldType.SEGMENT, "FTS", "File Trailer Segment", null),
  BHS("BHS", ProfileFieldType.SEGMENT, "BHS", "Batch Header Segment", null),
  BTS("BTS", ProfileFieldType.SEGMENT, "BTS", "Batch Trailer Segment", null),
  MSH("MSH", ProfileFieldType.SEGMENT, "MSH", "Message Header Segment", Usage.R),
  MSH_3("MSH-3", ProfileFieldType.FIELD, "MSH", "Sending Application", Usage.RE),
  MSH_3_1("MSH-3.1", ProfileFieldType.FIELD_PART, "MSH", " - Namespace ID", null),
  MSH_3_2("MSH-3.2", ProfileFieldType.FIELD_PART, "MSH", " - Universal ID", null),
  MSH_4("MSH-4", ProfileFieldType.FIELD, "MSH", "Sending Facility", Usage.RE),
  MSH_4_1("MSH-4.1", ProfileFieldType.FIELD_PART, "MSH", " - Namespace ID", null),
  MSH_4_2("MSH-4.2", ProfileFieldType.FIELD_PART, "MSH", " - Universal ID", null),
  MSH_5("MSH-5", ProfileFieldType.FIELD, "MSH", "Receiving Application", Usage.RE),
  MSH_5_1("MSH-5.1", ProfileFieldType.FIELD_PART, "MSH", " - Namespace ID", null),
  MSH_5_2("MSH-5.2", ProfileFieldType.FIELD_PART, "MSH", " - Universal ID", null),
  MSH_6("MSH-6", ProfileFieldType.FIELD, "MSH", "Receiving Facility", Usage.RE),
  MSH_6_1("MSH-6.1", ProfileFieldType.FIELD_PART, "MSH", " - Namespace ID", null),
  MSH_6_2("MSH-6.2", ProfileFieldType.FIELD_PART, "MSH", " - Universal ID", null),
  MSH_7("MSH-7", ProfileFieldType.FIELD, "MSH", "Date/time of message", Usage.R),
  MSH_7_TZ("MSH-7 TZ", ProfileFieldType.FIELD_PART, "MSH", " - Timezone", Usage.O),
  MSH_8("MSH-8", ProfileFieldType.FIELD, "MSH", "Security", Usage.O),
  MSH_9("MSH-9", ProfileFieldType.FIELD, "MSH", "Message type", Usage.R),
  MSH_10("MSH-10", ProfileFieldType.FIELD, "MSH", "Message control ID", Usage.R),
  MSH_11("MSH-11", ProfileFieldType.FIELD, "MSH", "Processing ID", Usage.R),
  MSH_12("MSH-12", ProfileFieldType.FIELD, "MSH", "HL7 Version ID", Usage.R),
  MSH_13("MSH-13", ProfileFieldType.FIELD, "MSH", "Sequence Number", Usage.O),
  MSH_14("MSH-14", ProfileFieldType.FIELD, "MSH", "Continuation Pointer", Usage.O),
  MSH_15("MSH-15", ProfileFieldType.FIELD, "MSH", "Accept Acknowledgement Type", Usage.R),
  MSH_16("MSH-16", ProfileFieldType.FIELD, "MSH", "Application Acknowledgement Type", Usage.R),
  MSH_17("MSH-17", ProfileFieldType.FIELD, "MSH", "Country Code", Usage.O),
  MSH_18("MSH-18", ProfileFieldType.FIELD, "MSH", "Character Set", Usage.O),
  MSH_19("MSH-19", ProfileFieldType.FIELD, "MSH", "Principal Language of Message", Usage.O),
  MSH_20("MSH-20", ProfileFieldType.FIELD, "MSH", "Alternate Character Set Handling Scheme", Usage.O),
  MSH_21("MSH-21", ProfileFieldType.FIELD, "MSH", "Message Profile Identifier", Usage.RE),
  MSH_22("MSH-22", ProfileFieldType.FIELD, "MSH", "Responsible Sending Organization", Usage.RE),
  MSH_23("MSH-23", ProfileFieldType.FIELD, "MSH", "Responsible Receiving Organization", Usage.RE),
  MSH_24("MSH-24", ProfileFieldType.FIELD, "MSH", "Sending Network Address", Usage.O),
  MSH_25("MSH-25", ProfileFieldType.FIELD, "MSH", "Receiving Network Address", Usage.O),
  SFT("SFT", ProfileFieldType.SEGMENT, "SFT", "Software Segment", Usage.O),
  PID("PID", ProfileFieldType.SEGMENT, "PID", "Patient Identification Segment", Usage.R),
  PID_1("PID-1", ProfileFieldType.FIELD, "PID", "Set ID - PID", Usage.O),
  PID_2("PID-2", ProfileFieldType.FIELD, "PID", "Patient ID", Usage.X),
  PID_3("PID-3", ProfileFieldType.FIELD, "PID", "Patient ID", Usage.R),
  PID_3_1("PID-3.1", ProfileFieldType.FIELD_PART, "PID", " - ID Number", Usage.R),
  PID_3_4("PID-3.4", ProfileFieldType.FIELD_PART, "PID", " - Assigning Authority", Usage.R),
  PID_3_5("PID-3.5", ProfileFieldType.FIELD_PART, "PID", " - Identifier Type", Usage.R),
  PID_3_SSN("PID-3 SSN", ProfileFieldType.FIELD, "PID", "Patient ID - SSN", Usage.O),
  PID_3_MEDICAID("PID-3 Medicaid", ProfileFieldType.FIELD, "PID", "Patient ID - Medicaid", Usage.O),
  PID_4("PID-4", ProfileFieldType.FIELD, "PID", "Alternate Patient ID - 00106", Usage.X),
  PID_5("PID-5", ProfileFieldType.FIELD, "PID", "Patient Name", Usage.R),
  PID_5_1("PID-5.1", ProfileFieldType.FIELD_PART, "PID", " - Family Name", Usage.R),
  PID_5_2("PID-5.2", ProfileFieldType.FIELD_PART, "PID", " - Given Name", Usage.R),
  PID_5_3("PID-5.3", ProfileFieldType.FIELD_PART, "PID", " - Second and Further Given Names or Initials Therof", Usage.RE),
  PID_5_4("PID-5.4", ProfileFieldType.FIELD_PART, "PID", " - Suffix", Usage.O),
  PID_5_5("PID-5.5", ProfileFieldType.FIELD_PART, "PID", " - Prefix", Usage.O),
  PID_5_6("PID-5.6", ProfileFieldType.FIELD_PART, "PID", " - Degree", Usage.X),
  PID_5_7("PID-5.7", ProfileFieldType.FIELD_PART, "PID", " - Name Type", Usage.RE),
  PID_5_8("PID-5.8", ProfileFieldType.FIELD_PART, "PID", " - Name Representation Code", Usage.O),
  PID_5_9("PID-5.9", ProfileFieldType.FIELD_PART, "PID", " - Name Context", Usage.O),
  PID_5_10("PID-5.10", ProfileFieldType.FIELD_PART, "PID", " - Name Validity Range", Usage.X),
  PID_5_11("PID-5.11", ProfileFieldType.FIELD_PART, "PID", " - Name Assembly Order", Usage.O),
  PID_5_12("PID-5.12", ProfileFieldType.FIELD_PART, "PID", " - Effective Date", Usage.O),
  PID_5_13("PID-5.13", ProfileFieldType.FIELD_PART, "PID", " - Expiration Date", Usage.O),
  PID_5_14("PID-5.14", ProfileFieldType.FIELD_PART, "PID", " - Professional Suffix", Usage.O),
  PID_5_ALIAS("PID-5 Alias", ProfileFieldType.FIELD, "PID", "Patient Name - Alias", Usage.O),
  PID_5_1_ALIAS("PID-5.1 Alias", ProfileFieldType.FIELD_PART, "PID", " - Family Name", Usage.R),
  PID_5_2_ALIAS("PID-5.2 Alias", ProfileFieldType.FIELD_PART, "PID", " - Given Name", Usage.R),
  PID_5_3_ALIAS("PID-5.3 Alias", ProfileFieldType.FIELD_PART, "PID", " - Second and Further Given Names or Initials Therof", Usage.RE),
  PID_5_4_ALIAS("PID-5.4 Alias", ProfileFieldType.FIELD_PART, "PID", " - Suffix", Usage.O),
  PID_5_7_ALIAS("PID-5.7 Alias", ProfileFieldType.FIELD_PART, "PID", " - Name Type", Usage.R),
  PID_6("PID-6", ProfileFieldType.FIELD, "PID", "Mother's Maiden Name", Usage.RE),
  PID_6_1("PID-6.1", ProfileFieldType.FIELD_PART, "PID", " - Family Name", Usage.R),
  PID_6_2("PID-6.2", ProfileFieldType.FIELD_PART, "PID", " - Given Name", Usage.RE),
  PID_6_3("PID-6.3", ProfileFieldType.FIELD_PART, "PID", " - Second and Further Given Names or Initials Therof", Usage.O),
  PID_6_7("PID-6.7", ProfileFieldType.FIELD_PART, "PID", " - Name Type", Usage.RE),
  PID_7("PID-7", ProfileFieldType.FIELD, "PID", "Date of Birth", Usage.R),
  PID_8("PID-8", ProfileFieldType.FIELD, "PID", "Administrative Sex", Usage.RE),
  PID_9("PID-9", ProfileFieldType.FIELD, "PID", "Patient Alias", Usage.X),
  PID_10("PID-10", ProfileFieldType.FIELD, "PID", "Race", Usage.RE),
  PID_11("PID-11", ProfileFieldType.FIELD, "PID", "Patient Address", Usage.RE),
  PID_11_1("PID-11.1", ProfileFieldType.FIELD_PART, "PID", " - Street Address", Usage.RE),
  PID_11_1_1("PID-11.1.1", ProfileFieldType.FIELD_SUB_PART, "PID", " - (Street or Mailing Address)", null),
  PID_11_1_2("PID-11.1.2", ProfileFieldType.FIELD_SUB_PART, "PID", " - (Street Name)", null),
  PID_11_1_3("PID-11.1.3", ProfileFieldType.FIELD_SUB_PART, "PID", " - (Dwelling Number)", null),
  PID_11_2("PID-11.2", ProfileFieldType.FIELD_PART, "PID", " - Other Designation", Usage.RE),
  PID_11_3("PID-11.3", ProfileFieldType.FIELD_PART, "PID", " - City", Usage.RE),
  PID_11_4("PID-11.4", ProfileFieldType.FIELD_PART, "PID", " - State or Province", Usage.RE),
  PID_11_5("PID-11.5", ProfileFieldType.FIELD_PART, "PID", " - Zip or Postal Code", Usage.RE),
  PID_11_6("PID-11.6", ProfileFieldType.FIELD_PART, "PID", " - Country", Usage.RE),
  PID_11_7("PID-11.7", ProfileFieldType.FIELD_PART, "PID", " - Address Type", Usage.R),
  PID_11_8("PID-11.8", ProfileFieldType.FIELD_PART, "PID", " - Other Geographic Designation", Usage.O),
  PID_11_9("PID-11.9", ProfileFieldType.FIELD_PART, "PID", " - County", Usage.O),
  PID_11_10("PID-11.10", ProfileFieldType.FIELD_PART, "PID", " - Census Tract", Usage.O),
  PID_11_11("PID-11.11", ProfileFieldType.FIELD_PART, "PID", " - Address Representation Code", Usage.O),
  PID_11_12("PID-11.12", ProfileFieldType.FIELD_PART, "PID", " - Address Validity Range", Usage.X),
  PID_11_13("PID-11.13", ProfileFieldType.FIELD_PART, "PID", " - Effective Date", Usage.O),
  PID_11_14("PID-11.14", ProfileFieldType.FIELD_PART, "PID", " - Expiration Date", Usage.O),
  PID_11_HOME("PID-11 Home", ProfileFieldType.FIELD, "PID", "Patient Address - Home", null),
  PID_11_BIRTH("PID-11 Birth", ProfileFieldType.FIELD, "PID", "Patient Address - Birth Delivery Location", null),
  PID_12("PID-12", ProfileFieldType.FIELD, "PID", "County Code", Usage.X),
  PID_13("PID-13", ProfileFieldType.FIELD, "PID", "Phone Number - Home", Usage.RE),
  PID_13_1("PID-13.1", ProfileFieldType.FIELD_PART, "PID", " - Telephone Number", Usage.X),
  PID_13_2("PID-13.2", ProfileFieldType.FIELD_PART, "PID", " - Telecommunication Use Code", Usage.R),
  PID_13_3("PID-13.3", ProfileFieldType.FIELD_PART, "PID", " - Telecommunication Equipment Type", Usage.RE),
  PID_13_4("PID-13.4", ProfileFieldType.FIELD_PART, "PID", " - Email Address", Usage.X),
  PID_13_5("PID-13.5", ProfileFieldType.FIELD_PART, "PID", " - Country Code", Usage.O),
  PID_13_6("PID-13.6", ProfileFieldType.FIELD_PART, "PID", " - Area/City Code", Usage.RE),
  PID_13_7("PID-13.7", ProfileFieldType.FIELD_PART, "PID", " - Local Number", Usage.R),
  PID_13_8("PID-13.8", ProfileFieldType.FIELD_PART, "PID", " - Extension", Usage.O),
  PID_13_9("PID-13.9", ProfileFieldType.FIELD_PART, "PID", " - Any Text", Usage.O),
  PID_13_10("PID-13.10", ProfileFieldType.FIELD_PART, "PID", " - Extension Prefix", Usage.O),
  PID_13_11("PID-13.11", ProfileFieldType.FIELD_PART, "PID", " - Speed Dial Code", Usage.O),
  PID_13_12("PID-13.12", ProfileFieldType.FIELD_PART, "PID", " - Unformatted Telephone number", Usage.O),
  PID_13_EMAIL("PID-13 Email", ProfileFieldType.FIELD, "PID", "Email", Usage.O),
  PID_13_CELL("PID-13 Cell", ProfileFieldType.FIELD, "PID", "Cell Phone", Usage.O),
  PID_13_FAX("PID-13 Fax", ProfileFieldType.FIELD, "PID", "Fax", Usage.O),
  PID_14("PID-14", ProfileFieldType.FIELD, "PID", "Phone Number - Business", Usage.O),
  PID_14_1("PID-14.1", ProfileFieldType.FIELD_PART, "PID", " - Telephone Number", Usage.X),
  PID_14_2("PID-14.2", ProfileFieldType.FIELD_PART, "PID", " - Telecommunication Use Code", Usage.R),
  PID_14_3("PID-14.3", ProfileFieldType.FIELD_PART, "PID", " - Telecommunication Equipment Type", Usage.RE),
  PID_14_6("PID-14.6", ProfileFieldType.FIELD_PART, "PID", " - Area/City Code", Usage.RE),
  PID_14_7("PID-14.7", ProfileFieldType.FIELD_PART, "PID", " - Local Number", Usage.R),
  PID_15("PID-15", ProfileFieldType.FIELD, "PID", "Primary Language", Usage.O),
  PID_16("PID-16", ProfileFieldType.FIELD, "PID", "Marital Status", Usage.O),
  PID_17("PID-17", ProfileFieldType.FIELD, "PID", "Religion", Usage.O),
  PID_18("PID-18", ProfileFieldType.FIELD, "PID", "Patient Account Number", Usage.O),
  PID_19("PID-19", ProfileFieldType.FIELD, "PID", "SSN Number - Patient", Usage.X),
  PID_20("PID-20", ProfileFieldType.FIELD, "PID", "Driver's License Number - Patient", Usage.X),
  PID_21("PID-21", ProfileFieldType.FIELD, "PID", "Mother's Identifier", Usage.X),
  PID_22("PID-22", ProfileFieldType.FIELD, "PID", "Ethnic Group", Usage.RE),
  PID_23("PID-23", ProfileFieldType.FIELD, "PID", "Birth Place", Usage.O),
  PID_24("PID-24", ProfileFieldType.FIELD, "PID", "Multiple Birth Indicator", Usage.RE),
  PID_25("PID-25", ProfileFieldType.FIELD, "PID", "Birth Order", Usage.RE),
  PID_26("PID-26", ProfileFieldType.FIELD, "PID", "Citizenship", Usage.O),
  PID_27("PID-27", ProfileFieldType.FIELD, "PID", "Veterans Military Status", Usage.O),
  PID_28("PID-28", ProfileFieldType.FIELD, "PID", "Nationality", Usage.O),
  PID_29("PID-29", ProfileFieldType.FIELD, "PID", "Patient Death Date and Time", Usage.RE),
  PID_30("PID-30", ProfileFieldType.FIELD, "PID", "Patient Death Indicator", Usage.RE),
  PID_31("PID-31", ProfileFieldType.FIELD, "PID", "Identify Unknown Indicator", Usage.O),
  PID_32("PID-32", ProfileFieldType.FIELD, "PID", "Identity Reliability Code", Usage.O),
  PID_33("PID-33", ProfileFieldType.FIELD, "PID", "Last Update Date/Time", Usage.O),
  PID_34("PID-34", ProfileFieldType.FIELD, "PID", "Last Update Facility", Usage.O),
  PID_35("PID-35", ProfileFieldType.FIELD, "PID", "Species Code", Usage.O),
  PID_36("PID-36", ProfileFieldType.FIELD, "PID", "Breed Code", Usage.O),
  PID_37("PID-37", ProfileFieldType.FIELD, "PID", "Strain", Usage.O),
  PID_38("PID-38", ProfileFieldType.FIELD, "PID", "Production Class Code", Usage.O),
  PID_39("PID-39", ProfileFieldType.FIELD, "PID", "Tribal Citizenship", Usage.O),
  PD1("PD1", ProfileFieldType.SEGMENT, "PD1", "Patient Additional Demographics Segment", Usage.RE),
  PD1_1("PD1-1", ProfileFieldType.FIELD, "PD1", "Living Dependency", Usage.O),
  PD1_2("PD1-2", ProfileFieldType.FIELD, "PD1", "Living Arrangement", Usage.O),
  PD1_3("PD1-3", ProfileFieldType.FIELD, "PD1", "Primary Care Provider ID", Usage.O),
  PD1_3_1("PD1-3.1", ProfileFieldType.FIELD_PART, "PD1", " - Organization Name", Usage.RE),
  PD1_3_2("PD1-3.2", ProfileFieldType.FIELD_PART, "PD1", " - Organization Name Type Code", Usage.O),
  PD1_3_3("PD1-3.3", ProfileFieldType.FIELD_PART, "PD1", " - ID Number", Usage.X),
  PD1_3_6("PD1-3.6", ProfileFieldType.FIELD_PART, "PD1", " - Assigning Authority", Usage.RE),
  PD1_3_7("PD1-3.7", ProfileFieldType.FIELD_PART, "PD1", " - Identifier Type Code", Usage.RE),
  PD1_3_10("PD1-3.10", ProfileFieldType.FIELD_PART, "PD1", " - Organization Identifier", Usage.RE),
  PD1_4("PD1-4", ProfileFieldType.FIELD, "PD1", "Primary Care Provider Name and ID", Usage.X),
  PD1_4_1("PD1-4.1", ProfileFieldType.FIELD_PART, "PD1", " - ID Number", null),
  PD1_4_2("PD1-4.2", ProfileFieldType.FIELD_PART, "PD1", " - Family Name", null),
  PD1_4_3("PD1-4.3", ProfileFieldType.FIELD_PART, "PD1", " - Given Name", null),
  PD1_4_4("PD1-4.4", ProfileFieldType.FIELD_PART, "PD1", " - Second and Further Given Names or Initials Therof", null),
  PD1_4_9("PD1-4.9", ProfileFieldType.FIELD_PART, "PD1", " - Assigning Authority", null),
  PD1_4_10("PD1-4.10", ProfileFieldType.FIELD_PART, "PD1", " - Name Type Code", null),
  PD1_4_13("PD1-4.13", ProfileFieldType.FIELD_PART, "PD1", " - Identifier Type Code", null),
  PD1_4_21("PD1-4.21", ProfileFieldType.FIELD_PART, "PD1", " - Professional Suffix", null),
  PD1_5("PD1-5", ProfileFieldType.FIELD, "PD1", "Student Indicator", Usage.O),
  PD1_6("PD1-6", ProfileFieldType.FIELD, "PD1", "Handicap", Usage.O),
  PD1_7("PD1-7", ProfileFieldType.FIELD, "PD1", "Living Will Code", Usage.O),
  PD1_8("PD1-8", ProfileFieldType.FIELD, "PD1", "Organ Donor Code", Usage.O),
  PD1_9("PD1-9", ProfileFieldType.FIELD, "PD1", "Separate Bill", Usage.O),
  PD1_10("PD1-10", ProfileFieldType.FIELD, "PD1", "Duplicate Patient", Usage.O),
  PD1_11("PD1-11", ProfileFieldType.FIELD, "PD1", "Publicity Code", Usage.RE),
  PD1_12("PD1-12", ProfileFieldType.FIELD, "PD1", "Protection Indicator", Usage.RE),
  PD1_13("PD1-13", ProfileFieldType.FIELD, "PD1", "Protection Indicator Effective Date", Usage.RE),
  PD1_14("PD1-14", ProfileFieldType.FIELD, "PD1", "Place of Worship", Usage.O),
  PD1_15("PD1-15", ProfileFieldType.FIELD, "PD1", "Advance Directive Code", Usage.O),
  PD1_16("PD1-16", ProfileFieldType.FIELD, "PD1", "Immunization Registry Status", Usage.RE),
  PD1_17("PD1-17", ProfileFieldType.FIELD, "PD1", "Immunization Registry Status Effective Date", Usage.RE),
  PD1_18("PD1-18", ProfileFieldType.FIELD, "PD1", "Publicity Code Effective Date", Usage.RE),
  PD1_19("PD1-19", ProfileFieldType.FIELD, "PD1", "Military Branch", Usage.O),
  PD1_20("PD1-20", ProfileFieldType.FIELD, "PD1", "Military Rank/Grade", Usage.O),
  PD1_21("PD1-21", ProfileFieldType.FIELD, "PD1", "Military Status", Usage.O),
  NK1("NK1", ProfileFieldType.SEGMENT, "NK1", "Next of Kin Segment", Usage.RE),
  NK1_1("NK1-1", ProfileFieldType.FIELD, "NK1", "Set ID - NK1", Usage.R),
  NK1_2("NK1-2", ProfileFieldType.FIELD, "NK1", "Next of Kin Name", Usage.R),
  NK1_2_1("NK1-2.1", ProfileFieldType.FIELD_PART, "NK1", " - Family Name", Usage.R),
  NK1_2_2("NK1-2.2", ProfileFieldType.FIELD_PART, "NK1", " - Given Name", Usage.R),
  NK1_2_3("NK1-2.3", ProfileFieldType.FIELD_PART, "NK1", " - Second and Further Given Names or Initials Therof", Usage.RE),
  NK1_2_7("NK1-2.7", ProfileFieldType.FIELD_PART, "NK1", " - Name Type Code", Usage.RE),
  NK1_3("NK1-3", ProfileFieldType.FIELD, "NK1", "Relationship", Usage.R),
  NK1_4("NK1-4", ProfileFieldType.FIELD, "NK1", "Address", Usage.RE),
  NK1_4_1("NK1-4.1", ProfileFieldType.FIELD_PART, "NK1", " - Street Address", Usage.RE),
  NK1_4_2("NK1-4.2", ProfileFieldType.FIELD_PART, "NK1", " - Other Designation", Usage.RE),
  NK1_4_3("NK1-4.3", ProfileFieldType.FIELD_PART, "NK1", " - City", Usage.RE),
  NK1_4_4("NK1-4.4", ProfileFieldType.FIELD_PART, "NK1", " - State or Province", Usage.RE),
  NK1_4_5("NK1-4.5", ProfileFieldType.FIELD_PART, "NK1", " - Zip or Postal Code", Usage.RE),
  NK1_4_6("NK1-4.6", ProfileFieldType.FIELD_PART, "NK1", " - Country", Usage.RE),
  NK1_4_7("NK1-4.7", ProfileFieldType.FIELD_PART, "NK1", " - Address Type", Usage.R),
  NK1_4_HOME("NK1-4 Home", ProfileFieldType.FIELD, "NK1", "Address - Home", null),
  NK1_5("NK1-5", ProfileFieldType.FIELD, "NK1", "Phone Number", Usage.RE),
  NK1_5_1("NK1-5.1", ProfileFieldType.FIELD_PART, "NK1", " - Telephone Number", Usage.X),
  NK1_5_2("NK1-5.2", ProfileFieldType.FIELD_PART, "NK1", " - Telecommunication Use Code", Usage.R),
  NK1_5_3("NK1-5.3", ProfileFieldType.FIELD_PART, "NK1", " - Telecommunication Equipment Type", Usage.RE),
  NK1_5_6("NK1-5.6", ProfileFieldType.FIELD_PART, "NK1", " - Area/City Code", Usage.RE),
  NK1_5_7("NK1-5.7", ProfileFieldType.FIELD_PART, "NK1", " - Local Number", Usage.R),
  NK1_5_CELL("NK1-5 Cell", ProfileFieldType.FIELD, "NK1", "Phone Number - Cell", null),
  NK1_5_EMAIL("NK1-5 Email", ProfileFieldType.FIELD, "NK1", "Phone Number - Email", null),
  NK1_5_FAX("NK1-5 Fax", ProfileFieldType.FIELD, "NK1", "Phone Number - Fax", null),
  NK1_6("NK1-6", ProfileFieldType.FIELD, "NK1", "Business Phone Number", Usage.O),
  NK1_6_1("NK1-6.1", ProfileFieldType.FIELD_PART, "NK1", " - Telephone Number", Usage.X),
  NK1_6_2("NK1-6.2", ProfileFieldType.FIELD_PART, "NK1", " - Telecommunication Use Code", Usage.R),
  NK1_6_3("NK1-6.3", ProfileFieldType.FIELD_PART, "NK1", " - Telecommunication Equipment Type", Usage.RE),
  NK1_6_6("NK1-6.6", ProfileFieldType.FIELD_PART, "NK1", " - Area/City Code", Usage.RE),
  NK1_6_7("NK1-6.7", ProfileFieldType.FIELD_PART, "NK1", " - Local Number", Usage.R),
  NK1_6_8("NK1.6.8", ProfileFieldType.FIELD_PART, "NK1", " - Extension", Usage.O),
  NK1_7("NK1-7", ProfileFieldType.FIELD, "NK1", "Contact Role", Usage.O),
  NK1_8("NK1-8", ProfileFieldType.FIELD, "NK1", "Start Date", Usage.O),
  NK1_9("NK1-9", ProfileFieldType.FIELD, "NK1", "End Date", Usage.O),
  NK1_10("NK1-10", ProfileFieldType.FIELD, "NK1", "Next of Kin / Associated Parties Job Title", Usage.O),
  NK1_11("NK1-11", ProfileFieldType.FIELD, "NK1", "Next of Kin / Associated Parties Job Code/Class", Usage.O),
  NK1_12("NK1-12", ProfileFieldType.FIELD, "NK1", "Next of Kin / Associated Parties Employee Number", Usage.O),
  NK1_13("NK1-13", ProfileFieldType.FIELD, "NK1", "Organization Name - NK1", Usage.O),
  NK1_14("NK1-14", ProfileFieldType.FIELD, "NK1", "Marital Status", Usage.O),
  NK1_15("NK1-15", ProfileFieldType.FIELD, "NK1", "Administrative Sex", Usage.O),
  NK1_16("NK1-16", ProfileFieldType.FIELD, "NK1", "Date/Time of Birth", Usage.O),
  NK1_17("NK1-17", ProfileFieldType.FIELD, "NK1", "Living Dependency", Usage.O),
  NK1_18("NK1-18", ProfileFieldType.FIELD, "NK1", "Ambulatory Status", Usage.O),
  NK1_19("NK1-19", ProfileFieldType.FIELD, "NK1", "Citizenship", Usage.O),
  NK1_20("NK1-20", ProfileFieldType.FIELD, "NK1", "Primary Language", Usage.O),
  NK1_21("NK1-21", ProfileFieldType.FIELD, "NK1", "Living Arrangement", Usage.O),
  NK1_22("NK1-22", ProfileFieldType.FIELD, "NK1", "Publicity Code", Usage.O),
  NK1_23("NK1-23", ProfileFieldType.FIELD, "NK1", "Protection Indicator", Usage.O),
  NK1_24("NK1-24", ProfileFieldType.FIELD, "NK1", "Student Indicator", Usage.O),
  NK1_25("NK1-25", ProfileFieldType.FIELD, "NK1", "Religion", Usage.O),
  NK1_26("NK1-26", ProfileFieldType.FIELD, "NK1", "Mother's Maiden Name", Usage.O),
  NK1_27("NK1-27", ProfileFieldType.FIELD, "NK1", "Nationality", Usage.O),
  NK1_28("NK1-28", ProfileFieldType.FIELD, "NK1", "Ethnic Group", Usage.O),
  NK1_29("NK1-29", ProfileFieldType.FIELD, "NK1", "Contact Reason", Usage.O),
  NK1_30("NK1-30", ProfileFieldType.FIELD, "NK1", "Contact Person's Name", Usage.O),
  NK1_31("NK1-31", ProfileFieldType.FIELD, "NK1", "Contact Person's Telephone Number", Usage.O),
  NK1_32("NK1-32", ProfileFieldType.FIELD, "NK1", "Contact Person's Address", Usage.O),
  NK1_33("NK1-33", ProfileFieldType.FIELD, "NK1", "Next of Kin/Associated Party's Identifiers", Usage.O),
  NK1_34("NK1-34", ProfileFieldType.FIELD, "NK1", "Job Status", Usage.O),
  NK1_35("NK1-35", ProfileFieldType.FIELD, "NK1", "Race", Usage.O),
  NK1_36("NK1-36", ProfileFieldType.FIELD, "NK1", "Handicap", Usage.O),
  NK1_37("NK1-37", ProfileFieldType.FIELD, "NK1", "Contact Person Social Security Number", Usage.O),
  NK1_38("NK1-38", ProfileFieldType.FIELD, "NK1", "Next of Kin Birth Place", Usage.O),
  NK1_39("NK1-39", ProfileFieldType.FIELD, "NK1", "VIP Indicator", Usage.O),
  PV1("PV1", ProfileFieldType.SEGMENT, "PV1", "Patient Visit Segment", Usage.O),
  PV1_1("PV1-1", ProfileFieldType.FIELD, "PV1", "Set ID - PV1", null),
  PV1_2("PV1-2", ProfileFieldType.FIELD, "PV1", "Patient class", null),
  PV1_7("PV1-7", ProfileFieldType.FIELD, "PV1", "Attending doctor", null),
  PV1_7_1("PV1-7.1", ProfileFieldType.FIELD_PART, "PV1", " - ID Number", null),
  PV1_7_2("PV1-7.2", ProfileFieldType.FIELD_PART, "PV1", " - Family Name", null),
  PV1_7_3("PV1-7.3", ProfileFieldType.FIELD_PART, "PV1", " - Given Name", null),
  PV1_7_4("PV1-7.4", ProfileFieldType.FIELD_PART, "PV1", " - Second and Further Given Names or Initials Therof", null),
  PV1_19("PV1-19", ProfileFieldType.FIELD, "PV1", "Visit number", null),
  PV1_20("PV1-20", ProfileFieldType.FIELD, "PV1", "Financial Class", Usage.X),
  PV1_20_1("PV1-20.1", ProfileFieldType.FIELD_PART, "PV1", " - Financial Class Code", null),
  PV1_20_2("PV1-20.2", ProfileFieldType.FIELD_PART, "PV1", " - Effective Date", null),
  PV1_44("PV1-44", ProfileFieldType.FIELD, "PV1", "Admit date/time", null),
  PV2("PV2", ProfileFieldType.SEGMENT, "PV2", "Patient Visit Segment 2", Usage.O),
  GT1("GT1", ProfileFieldType.SEGMENT, "GT1", "Guarantor Segment", Usage.O),
  IN1_GROUP("IN1 Group", ProfileFieldType.SEGMENT, "IN1", "Insurance Group", Usage.O),
  IN1("IN1", ProfileFieldType.SEGMENT, "IN1", "Insurance Segment", Usage.O),
  IN1_1("IN1-1", ProfileFieldType.FIELD, "IN1", "Set ID - IN1", Usage.R),
  IN1_2("IN1-2", ProfileFieldType.FIELD, "IN1", "Insurance Plan ID", Usage.R),
  IN1_3("IN1-3", ProfileFieldType.FIELD, "IN1", "Insurance Company ID", Usage.R),
  IN1_4("IN1-4", ProfileFieldType.FIELD, "IN1", "Insurance Company Name", Usage.O),
  IN1_5("IN1-5", ProfileFieldType.FIELD, "IN1", "Insurance Company Address", Usage.O),
  IN1_6("IN1-6", ProfileFieldType.FIELD, "IN1", "Insurance Co Contact Person", Usage.O),
  IN1_7("IN1-7", ProfileFieldType.FIELD, "IN1", "Insurance Co Phone Number", Usage.O),
  IN1_8("IN1-8", ProfileFieldType.FIELD, "IN1", "Group Number", Usage.O),
  IN1_9("IN1-9", ProfileFieldType.FIELD, "IN1", "Group Name", Usage.O),
  IN1_10("IN1-10", ProfileFieldType.FIELD, "IN1", "Insured's Group Emp ID", Usage.O),
  IN1_11("IN1-11", ProfileFieldType.FIELD, "IN1", "Insured's Group Emp Name", Usage.O),
  IN1_12("IN1-12", ProfileFieldType.FIELD, "IN1", "Plan Effective Date", Usage.O),
  IN1_13("IN1-13", ProfileFieldType.FIELD, "IN1", "Plan Expiration Date", Usage.O),
  IN1_14("IN1-14", ProfileFieldType.FIELD, "IN1", "Authorization Information", Usage.O),
  IN1_15("IN1-15", ProfileFieldType.FIELD, "IN1", "Plan Type", Usage.R),
  IN1_16("IN1-16", ProfileFieldType.FIELD, "IN1", "Name of Insured", Usage.O),
  IN1_17("IN1-17", ProfileFieldType.FIELD, "IN1", "Insured's Relationship to Patient", Usage.O),
  IN1_18("IN1-18", ProfileFieldType.FIELD, "IN1", "Insured's Date of Birth", Usage.O),
  IN1_19("IN1-19", ProfileFieldType.FIELD, "IN1", "Insured's Address", Usage.O),
  IN1_20("IN1-20", ProfileFieldType.FIELD, "IN1", "Assignment of Benefits", Usage.O),
  IN1_21("IN1-21", ProfileFieldType.FIELD, "IN1", "Coordination of Benefits", Usage.O),
  IN1_22("IN1-22", ProfileFieldType.FIELD, "IN1", "Coord of Ben Priority", Usage.O),
  IN1_23("IN1-23", ProfileFieldType.FIELD, "IN1", "Notice Of Adminission Flag", Usage.O),
  IN1_24("IN1-24", ProfileFieldType.FIELD, "IN1", "Notice Of Admission Date", Usage.O),
  IN1_25("IN1-25", ProfileFieldType.FIELD, "IN1", "Report Of Eligibility Flag", Usage.O),
  IN1_26("IN1-26", ProfileFieldType.FIELD, "IN1", "Report Of Eligibility Date", Usage.O),
  IN1_27("IN1-27", ProfileFieldType.FIELD, "IN1", "Release Information Code", Usage.O),
  IN1_28("IN1-28", ProfileFieldType.FIELD, "IN1", "Pre-Admin Cert (PAC)", Usage.O),
  IN1_29("IN1-29", ProfileFieldType.FIELD, "IN1", "Verification Date/Time", Usage.RE),
  IN1_30("IN1-30", ProfileFieldType.FIELD, "IN1", "Verification By", Usage.O),
  IN1_31("IN1-31", ProfileFieldType.FIELD, "IN1", "Type of Agreemetn Code", Usage.O),
  IN1_32("IN1-32", ProfileFieldType.FIELD, "IN1", "Billing Status", Usage.O),
  IN1_33("IN1-33", ProfileFieldType.FIELD, "IN1", "Lifetime Reserve Days", Usage.O),
  IN1_34("IN1-34", ProfileFieldType.FIELD, "IN1", "Delay Before L.R. Day", Usage.O),
  IN1_35("IN1-35", ProfileFieldType.FIELD, "IN1", "Company Plan Code", Usage.O),
  IN1_36("IN1-36", ProfileFieldType.FIELD, "IN1", "Policy Number", Usage.O),
  IN1_37("IN1-37", ProfileFieldType.FIELD, "IN1", "Policy Deductible", Usage.O),
  IN1_38("IN1-38", ProfileFieldType.FIELD, "IN1", "Policy Limit - Amount", Usage.X),
  IN1_39("IN1-39", ProfileFieldType.FIELD, "IN1", "Policy Limit - Days", Usage.O),
  IN1_40("IN1-40", ProfileFieldType.FIELD, "IN1", "Room Rate - Semi-Private", Usage.X),
  IN1_41("IN1-41", ProfileFieldType.FIELD, "IN1", "Room Rate - Private", Usage.X),
  IN1_42("IN1-42", ProfileFieldType.FIELD, "IN1", "Insured's Employment Status", Usage.O),
  IN1_43("IN1-43", ProfileFieldType.FIELD, "IN1", "Insured's Administrative Sex", Usage.O),
  IN1_44("IN1-44", ProfileFieldType.FIELD, "IN1", "Insured's Employer's Address", Usage.O),
  IN1_45("IN1-45", ProfileFieldType.FIELD, "IN1", "Verification Status", Usage.O),
  IN1_46("IN1-46", ProfileFieldType.FIELD, "IN1", "Prior Insurance Plan ID", Usage.O),
  IN1_47("IN1-47", ProfileFieldType.FIELD, "IN1", "Coverage Tips", Usage.O),
  IN1_48("IN1-48", ProfileFieldType.FIELD, "IN1", "Handicap", Usage.O),
  IN1_49("IN1-49", ProfileFieldType.FIELD, "IN1", "Insured's ID Number", Usage.O),
  IN1_50("IN1-50", ProfileFieldType.FIELD, "IN1", "Signature Code", Usage.O),
  IN1_51("IN1-51", ProfileFieldType.FIELD, "IN1", "Signature Code Date", Usage.O),
  IN1_52("IN1-52", ProfileFieldType.FIELD, "IN1", "Insured's Birth Place", Usage.O),
  IN1_53("IN1-53", ProfileFieldType.FIELD, "IN1", "VIP Indicator", Usage.O),
  IN2("IN2", ProfileFieldType.SEGMENT, "IN1", "Insurance Segment 2", Usage.O),
  IN3("IN3", ProfileFieldType.SEGMENT, "IN1", "Insurance Segment 3", Usage.O),
  ORC_GROUP("ORC Group", ProfileFieldType.SEGMENT, "ORC", "Order Request Group", Usage.RE),
  ORC("ORC", ProfileFieldType.SEGMENT, "ORC", "Order Request Segment", Usage.R),
  ADMIN_ORC("Admin ORC", ProfileFieldType.SEGMENT, "ORC", "Order Request Segment", Usage.R),
  ADMIN_ORC_1("Admin ORC-1", ProfileFieldType.FIELD, "ORC", "Order Control", Usage.R),
  ADMIN_ORC_2("Admin ORC-2", ProfileFieldType.FIELD, "ORC", "Placer Order Number", Usage.RE),
  ADMIN_ORC_2_1("Admin ORC-2.1", ProfileFieldType.FIELD_PART, "ORC", " - Entity Identifier", Usage.R),
  ADMIN_ORC_2_2("Admin ORC-2.2", ProfileFieldType.FIELD_PART, "ORC", " - Namespace ID", Usage.RE),
  ADMIN_ORC_2_3("Admin ORC-2.3", ProfileFieldType.FIELD_PART, "ORC", " - Universal ID", Usage.RE),
  ADMIN_ORC_3("Admin ORC-3", ProfileFieldType.FIELD, "ORC", "Filler Order Number", Usage.R),
  ADMIN_ORC_3_1("Admin ORC-3.1", ProfileFieldType.FIELD_PART, "ORC", " - Entity Identifier", Usage.R),
  ADMIN_ORC_3_2("Admin ORC-3.2", ProfileFieldType.FIELD_PART, "ORC", " - Namespace ID", Usage.RE),
  ADMIN_ORC_3_3("Admin ORC-3.3", ProfileFieldType.FIELD_PART, "ORC", " - Universal ID", Usage.RE),
  ADMIN_ORC_4("Admin ORC-4", ProfileFieldType.FIELD, "ORC", "Placer Group Number", Usage.O),
  ADMIN_ORC_5("Admin ORC-5", ProfileFieldType.FIELD, "ORC", "Order Status", Usage.O),
  ADMIN_ORC_6("Admin ORC-6", ProfileFieldType.FIELD, "ORC", "Response Flag", Usage.O),
  ADMIN_ORC_7("Admin ORC-7", ProfileFieldType.FIELD, "ORC", "Quantity/Timing", Usage.X),
  ADMIN_ORC_8("Admin ORC-8", ProfileFieldType.FIELD, "ORC", "Parent", Usage.O),
  ADMIN_ORC_9("Admin ORC-9", ProfileFieldType.FIELD, "ORC", "Date/Time of Transaction", Usage.O),
  ADMIN_ORC_10("Admin ORC-10", ProfileFieldType.FIELD, "ORC", "Entered By", Usage.RE),
  ADMIN_ORC_10_1("Admin ORC-10.1", ProfileFieldType.FIELD_PART, "ORC", " - ID Number", Usage.RE),
  ADMIN_ORC_10_2("Admin ORC-10.2", ProfileFieldType.FIELD_PART, "ORC", " - Family Name", Usage.RE),
  ADMIN_ORC_10_3("Admin ORC-10.3", ProfileFieldType.FIELD_PART, "ORC", " - Given Name", Usage.RE),
  ADMIN_ORC_10_4("Admin ORC-10.4", ProfileFieldType.FIELD_PART, "ORC", " - Second and Further Given Names or Initials Therof", Usage.RE),
  ADMIN_ORC_10_9("Admin ORC-10.9", ProfileFieldType.FIELD_PART, "ORC", " - Assigning Authority", Usage.RE),
  ADMIN_ORC_10_10("Admin ORC-10.10", ProfileFieldType.FIELD_PART, "ORC", " - Name Type Code", Usage.RE),
  ADMIN_ORC_11("Admin ORC-11", ProfileFieldType.FIELD, "ORC", "Verified By", Usage.O),
  ADMIN_ORC_12("Admin ORC-12", ProfileFieldType.FIELD, "ORC", "Ordering Provider", Usage.RE),
  ADMIN_ORC_12_1("Admin ORC-12.1", ProfileFieldType.FIELD_PART, "ORC", " - ID Number", Usage.RE),
  ADMIN_ORC_12_2("Admin ORC-12.2", ProfileFieldType.FIELD_PART, "ORC", " - Family Name", Usage.RE),
  ADMIN_ORC_12_3("Admin ORC-12.3", ProfileFieldType.FIELD_PART, "ORC", " - Given Name", Usage.RE),
  ADMIN_ORC_12_4("Admin ORC-12.4", ProfileFieldType.FIELD_PART, "ORC", " - Second and Further Given Names or Initials Therof", Usage.RE),
  ADMIN_ORC_12_7("Admin ORC-12.7", ProfileFieldType.FIELD_PART, "ORC", " - Degree", Usage.X),
  ADMIN_ORC_12_9("Admin ORC-12.9", ProfileFieldType.FIELD_PART, "ORC", " - Assigning Authority", Usage.RE),
  ADMIN_ORC_12_10("Admin ORC-12.10", ProfileFieldType.FIELD_PART, "ORC", " - Name Type Code", Usage.RE),
  ADMIN_ORC_13("Admin ORC-13", ProfileFieldType.FIELD, "ORC", "Enterer's Location", Usage.O),
  ADMIN_ORC_14("Admin ORC-14", ProfileFieldType.FIELD, "ORC", "Call Back Phone Number", Usage.O),
  ADMIN_ORC_15("Admin ORC-15", ProfileFieldType.FIELD, "ORC", "Order Effective Date/Time", Usage.O),
  ADMIN_ORC_16("Admin ORC-16", ProfileFieldType.FIELD, "ORC", "Order Control Code Reason", Usage.O),
  ADMIN_ORC_17("Admin ORC-17", ProfileFieldType.FIELD, "ORC", "Entering Organization", Usage.RE),
  ADMIN_ORC_17_1("Admin ORC-17.1", ProfileFieldType.FIELD_PART, "ORC", " - Facility Id", Usage.R),
  ADMIN_ORC_17_4("Admin ORC-17.4", ProfileFieldType.FIELD_PART, "ORC", " - Facility Id Alt", Usage.O),
  ADMIN_ORC_18("Admin ORC-18", ProfileFieldType.FIELD, "ORC", "Entering Device", Usage.O),
  ADMIN_ORC_19("Admin ORC-19", ProfileFieldType.FIELD, "ORC", "Action By", Usage.O),
  ADMIN_ORC_20("Admin ORC-20", ProfileFieldType.FIELD, "ORC", "Advanced Beneficiary Notice Code", Usage.O),
  ADMIN_ORC_21("Admin ORC-21", ProfileFieldType.FIELD, "ORC", "Ordering Facility Name", Usage.O),
  ADMIN_ORC_22("Admin ORC-22", ProfileFieldType.FIELD, "ORC", "Ordering Facility Address", Usage.O),
  ADMIN_ORC_23("Admin ORC-23", ProfileFieldType.FIELD, "ORC", "Ordering Facility Phone Number", Usage.O),
  ADMIN_ORC_24("Admin ORC-24", ProfileFieldType.FIELD, "ORC", "Order Provider Address", Usage.O),
  ADMIN_ORC_25("Admin ORC-25", ProfileFieldType.FIELD, "ORC", "Order Status Modifier", Usage.O),
  ADMIN_ORC_26("Admin ORC-26", ProfileFieldType.FIELD, "ORC", "Advanced Beneficiary Notice Override Reason", Usage.O),
  ADMIN_ORC_27("Admin ORC-27", ProfileFieldType.FIELD, "ORC", "Filler's Expected Availability Date/Time", Usage.O),
  ADMIN_ORC_28("Admin ORC-28", ProfileFieldType.FIELD, "ORC", "Confidentiality Code", Usage.O),
  ADMIN_ORC_29("Admin ORC-29", ProfileFieldType.FIELD, "ORC", "Order Type", Usage.O),
  ADMIN_ORC_30("Admin ORC-30", ProfileFieldType.FIELD, "ORC", "Enterer Authorization Mode", Usage.O),
  ADMIN_ORC_31("Admin ORC-31", ProfileFieldType.FIELD, "ORC", "Parent Universal Service Identifier", Usage.O),
  TQ1("TQ1", ProfileFieldType.SEGMENT, "TQ1", "Timing and Quantity Segment 1", Usage.O),
  TQ2("TQ2", ProfileFieldType.SEGMENT, "TQ2", "Timing and Quantity Segment 2", Usage.O),
  ADMIN_RXA("Admin RXA", ProfileFieldType.SEGMENT, "RXA", "Pharmacy Administration Segment - Administered", Usage.R),
  ADMIN_RXA_1("Admin RXA-1", ProfileFieldType.FIELD, "RXA", "Give Sub-ID Counter", Usage.R),
  ADMIN_RXA_2("Admin RXA-2", ProfileFieldType.FIELD, "RXA", "Administration Sub-ID Counter", Usage.R),
  ADMIN_RXA_3("Admin RXA-3", ProfileFieldType.FIELD, "RXA", "Date/Time Start of Administration", Usage.R),
  ADMIN_RXA_4("Admin RXA-4", ProfileFieldType.FIELD, "RXA", "Date/Time End of Administration", Usage.RE),
  ADMIN_RXA_5("Admin RXA-5", ProfileFieldType.FIELD, "RXA", "Administration Code", Usage.R),
  ADMIN_RXA_6("Admin RXA-6", ProfileFieldType.FIELD, "RXA", "Administered Amount", Usage.R),
  ADMIN_RXA_7("Admin RXA-7", ProfileFieldType.FIELD, "RXA", "Administered Units", Usage.RE),
  ADMIN_RXA_8("Admin RXA-8", ProfileFieldType.FIELD, "RXA", "Administered Dosage Form", Usage.O),
  ADMIN_RXA_9("Admin RXA-9", ProfileFieldType.FIELD, "RXA", "Administered Notes", Usage.R),
  ADMIN_RXA_9_FREE("Admin RXA-9 Free", ProfileFieldType.FIELD, "RXA", "Administered Notes - Free Text", Usage.X),
  ADMIN_RXA_10("Admin RXA-10", ProfileFieldType.FIELD, "RXA", "Administering Provider", Usage.RE),
  ADMIN_RXA_10_1("Admin RXA-10.1", ProfileFieldType.FIELD_PART, "RXA", " - ID Number", Usage.RE),
  ADMIN_RXA_10_2("Admin RXA-10.2", ProfileFieldType.FIELD_PART, "RXA", " - Family Name", Usage.RE),
  ADMIN_RXA_10_3("Admin RXA-10.3", ProfileFieldType.FIELD_PART, "RXA", " - Given Name", Usage.RE),
  ADMIN_RXA_10_4("Admin RXA-10.4", ProfileFieldType.FIELD_PART, "RXA", " - Second and Further Given Names or Initials Therof", Usage.RE),
  ADMIN_RXA_10_5("Admin RXA-10.5", ProfileFieldType.FIELD_PART, "RXA", " - Suffix", Usage.O),
  ADMIN_RXA_10_6("Admin RXA-10.6", ProfileFieldType.FIELD_PART, "RXA", " - Prefix", Usage.O),
  ADMIN_RXA_10_7("Admin RXA-10.7", ProfileFieldType.FIELD_PART, "RXA", " - Degree", Usage.X),
  ADMIN_RXA_10_8("Admin RXA-10.8", ProfileFieldType.FIELD_PART, "RXA", " - Source Table", Usage.O),
  ADMIN_RXA_10_9("Admin RXA-10.9", ProfileFieldType.FIELD_PART, "RXA", " - Assigning Authority", Usage.RE),
  ADMIN_RXA_10_10("Admin RXA-10.10", ProfileFieldType.FIELD_PART, "RXA", " - Name Type Code", Usage.RE),
  ADMIN_RXA_10_11("Admin RXA-10.11", ProfileFieldType.FIELD_PART, "RXA", " - Identifier Check Digit", Usage.O),
  ADMIN_RXA_10_12("Admin RXA-10.12", ProfileFieldType.FIELD_PART, "RXA", " - Check Digit Scheme", Usage.O),
  ADMIN_RXA_10_13("Admin RXA-10.13", ProfileFieldType.FIELD_PART, "RXA", " - Identifier Type Code", Usage.O),
  ADMIN_RXA_10_14("Admin RXA-10.14", ProfileFieldType.FIELD_PART, "RXA", " - Assigning Facility", Usage.O),
  ADMIN_RXA_10_15("Admin RXA-10.15", ProfileFieldType.FIELD_PART, "RXA", " - Name Representation Code", Usage.O),
  ADMIN_RXA_10_16("Admin RXA-10.16", ProfileFieldType.FIELD_PART, "RXA", " - Name Context", Usage.O),
  ADMIN_RXA_10_17("Admin RXA-10.17", ProfileFieldType.FIELD_PART, "RXA", " - Name Validity Range", Usage.X),
  ADMIN_RXA_10_18("Admin RXA-10.18", ProfileFieldType.FIELD_PART, "RXA", " - Name Assembly Order", Usage.X),
  ADMIN_RXA_10_19("Admin RXA-10.19", ProfileFieldType.FIELD_PART, "RXA", " - Effective Date", Usage.O),
  ADMIN_RXA_10_20("Admin RXA-10.20", ProfileFieldType.FIELD_PART, "RXA", " - Expiration Date", Usage.O),
  ADMIN_RXA_10_21("Admin RXA-10.21", ProfileFieldType.FIELD_PART, "RXA", " - Professional Suffix", Usage.O),
  ADMIN_RXA_10_22("Admin RXA-10.22", ProfileFieldType.FIELD_PART, "RXA", " - Assigning Jurisdiction", Usage.O),
  ADMIN_RCA_10_23("Admin RCA-10.23", ProfileFieldType.FIELD_PART, "RXA", " - Assigning Agency or Department", Usage.O),
  ADMIN_RXA_11("Admin RXA-11", ProfileFieldType.FIELD, "RXA", "Administered-at Location", Usage.RE),
  ADMIN_RXA_11_1("Admin RXA-11.1", ProfileFieldType.FIELD_PART, "RXA", " - Point of Care", Usage.O),
  ADMIN_RXA_11_2("Admin RXA-11.2", ProfileFieldType.FIELD_PART, "RXA", " - Room", Usage.O),
  ADMIN_RXA_11_3("Admin RXA-11.3", ProfileFieldType.FIELD_PART, "RXA", " - Bed", Usage.O),
  ADMIN_RXA_11_4("Admin RXA-11.4", ProfileFieldType.FIELD_PART, "RXA", " - Facility", Usage.R),
  ADMIN_RXA_11_5("Admin RXA-11.5", ProfileFieldType.FIELD_PART, "RXA", " - Location Status", Usage.O),
  ADMIN_RXA_11_6("Admin RXA-11.6", ProfileFieldType.FIELD_PART, "RXA", " - Patient Location Type", Usage.O),
  ADMIN_RXA_11_7("Admin RXA-11.7", ProfileFieldType.FIELD_PART, "RXA", " - Building", Usage.O),
  ADMIN_RXA_11_8("Admin RXA-11.8", ProfileFieldType.FIELD_PART, "RXA", " - Floor", Usage.O),
  ADMIN_RXA_11_9("Admin RXA-11.9", ProfileFieldType.FIELD_PART, "RXA", " - Street Address", Usage.O),
  ADMIN_RXA_11_10("Admin RXA-11.10", ProfileFieldType.FIELD_PART, "RXA", " - Other Designation", Usage.O),
  ADMIN_RXA_11_11("Admin RXA-11.11", ProfileFieldType.FIELD_PART, "RXA", " - City", Usage.O),
  ADMIN_RXA_11_12("Admin RXA-11.12", ProfileFieldType.FIELD_PART, "RXA", " - State or Province", Usage.O),
  ADMIN_RXA_11_13("Admin RXA-11.13", ProfileFieldType.FIELD_PART, "RXA", " - Zip or Postal Code", Usage.O),
  ADMIN_RXA_11_14("Admin RXA-11.14", ProfileFieldType.FIELD_PART, "RXA", " - Country", Usage.O),
  ADMIN_RXA_11_15("Admin RXA-11.15", ProfileFieldType.FIELD_PART, "RXA", " - Address Type", Usage.O),
  ADMIN_RXA_11_16("Admin RXA-11.16", ProfileFieldType.FIELD_PART, "RXA", " - Other Geographic Designation", Usage.O),
  ADMIN_RXA_12("Admin RXA-12", ProfileFieldType.FIELD, "RXA", "Administered Per (Time Unit)", Usage.O),
  ADMIN_RXA_13("Admin RXA-13", ProfileFieldType.FIELD, "RXA", "Administered Strength", Usage.O),
  ADMIN_RXA_14("Admin RXA-14", ProfileFieldType.FIELD, "RXA", "Administered Strength Units", Usage.O),
  ADMIN_RXA_15("Admin RXA-15", ProfileFieldType.FIELD, "RXA", "Substance Lot Number", Usage.RE),
  ADMIN_RXA_16("Admin RXA-16", ProfileFieldType.FIELD, "RXA", "Substance Expiration Date", Usage.RE),
  ADMIN_RXA_16_YM("Admin RXA-16 YM", ProfileFieldType.FIELD, "RXA", " - Year and month only", Usage.O),
  ADMIN_RXA_17("Admin RXA-17", ProfileFieldType.FIELD, "RXA", "Substance Lot Mfr Name", Usage.RE),
  ADMIN_RXA_18("Admin RXA-18", ProfileFieldType.FIELD, "RXA", "Substance/Treatment Refusal Reason", Usage.X),
  ADMIN_RXA_19("Admin RXA-19", ProfileFieldType.FIELD, "RXA", "Indication", Usage.O),
  ADMIN_RXA_20("Admin RXA-20", ProfileFieldType.FIELD, "RXA", "Completion Status", Usage.RE),
  ADMIN_RXA_21("Admin RXA-21", ProfileFieldType.FIELD, "RXA", "Action Code", Usage.R),
  ADMIN_RXA_22("Admin RXA-22", ProfileFieldType.FIELD, "RXA", "System Entry Date/Time", Usage.O),
  ADMIN_RXA_23("Admin RXA-23", ProfileFieldType.FIELD, "RXA", "Administered Drug Strength Volume", Usage.O),
  ADMIN_RXA_24("Admin RXA-24", ProfileFieldType.FIELD, "RXA", "Administered Drug Strength Volume Units", Usage.O),
  ADMIN_RXA_25("Admin RXA-25", ProfileFieldType.FIELD, "RXA", "Administered Barcode Identifier", Usage.O),
  ADMIN_RXA_26("Admin RXA-26", ProfileFieldType.FIELD, "RXA", "Pharmacy Order Type", Usage.O),
  ADMIN_RXR("Admin RXR", ProfileFieldType.SEGMENT, "RXR", "Route of Administration Segment", Usage.RE),
  ADMIN_RXR_1("Admin RXR-1", ProfileFieldType.FIELD, "RXR", "Route", Usage.R),
  ADMIN_RXR_2("Admin RXR-2", ProfileFieldType.FIELD, "RXR", "Administration Site", Usage.RE),
  ADMIN_RXR_3("Admin RXR-3", ProfileFieldType.FIELD, "RXR", "Administration Device", Usage.O),
  ADMIN_RXR_4("Admin RXR-4", ProfileFieldType.FIELD, "RXR", "Administration Method", Usage.O),
  ADMIN_RXR_5("Admin RXR-5", ProfileFieldType.FIELD, "RXR", "Routing Instruction", Usage.O),
  ADMIN_RXR_6("Admin RXR-6", ProfileFieldType.FIELD, "RXR", "Administration Site Modifier", Usage.O),
  ADMIN_OBX("Admin OBX", ProfileFieldType.SEGMENT, "OBX", "Observation Segment", Usage.R),
  ADMIN_OBX_1("Admin OBX-1", ProfileFieldType.FIELD, "OBX", "Set ID – OBX", Usage.R),
  ADMIN_OBX_2("Admin OBX-2", ProfileFieldType.FIELD, "OBX", "Value Type", Usage.R),
  ADMIN_OBX_3("Admin OBX-3", ProfileFieldType.FIELD, "OBX", "Observation Identifier", Usage.R),
  ADMIN_OBX_4("Admin OBX-4", ProfileFieldType.FIELD, "OBX", "Observation Sub-ID", Usage.R),
  ADMIN_OBX_5("Admin OBX-5", ProfileFieldType.FIELD, "OBX", "Observation Value", Usage.R),
  ADMIN_OBX_6("Admin OBX-6", ProfileFieldType.FIELD, "OBX", "Units", Usage.O),
  ADMIN_OBX_7("Admin OBX-7", ProfileFieldType.FIELD, "OBX", "Reference Range", Usage.O),
  ADMIN_OBX_8("Admin OBX-8", ProfileFieldType.FIELD, "OBX", "Abnormal Flags", Usage.O),
  ADMIN_OBX_9("Admin OBX-9", ProfileFieldType.FIELD, "OBX", "Probability", Usage.O),
  ADMIN_OBX_10("Admin OBX-10", ProfileFieldType.FIELD, "OBX", "Nature of Abnormal Test", Usage.O),
  ADMIN_OBX_11("Admin OBX-11", ProfileFieldType.FIELD, "OBX", "Observation Result Status", Usage.R),
  ADMIN_OBX_12("Admin OBX-12", ProfileFieldType.FIELD, "OBX", "Effective Date of Reference Range Values", Usage.O),
  ADMIN_OBX_13("Admin OBX-13", ProfileFieldType.FIELD, "OBX", "User Defined Access Checks", Usage.O),
  ADMIN_OBX_14("Admin OBX-14", ProfileFieldType.FIELD, "OBX", "Date/Time of the Observation", Usage.RE),
  ADMIN_OBX_15("Admin OBX-15", ProfileFieldType.FIELD, "OBX", "Prodcucer's Reference", Usage.O),
  ADMIN_OBX_16("Admin OBX-16", ProfileFieldType.FIELD, "OBX", "Responsible Observer", Usage.O),
  ADMIN_OBX_17("Admin OBX-17", ProfileFieldType.FIELD, "OBX", "Observation Method", Usage.RE),
  ADMIN_OBX_18("Admin OBX-18", ProfileFieldType.FIELD, "OBX", "Equipment Instance Identifier", Usage.O),
  ADMIN_OBX_19("Admin OBX-19", ProfileFieldType.FIELD, "OBX", "Date/time of Analysis", Usage.O),
  ADMIN_OBX_20("Admin OBX-20", ProfileFieldType.FIELD, "OBX", "Reserved for harmonization with V2.6", Usage.X),
  ADMIN_OBX_21("Admin OBX-21", ProfileFieldType.FIELD, "OBX", "Reserved for harmonization with V2.6", Usage.X),
  ADMIN_OBX_22("Admin OBX-22", ProfileFieldType.FIELD, "OBX", "Reserved for harmonization with V2.6", Usage.X),
  ADMIN_OBX_23("Admin OBX-23", ProfileFieldType.FIELD, "OBX", "Performing Organization Name", Usage.O),
  ADMIN_OBX_24("Admin OBX-24", ProfileFieldType.FIELD, "OBX", "Performing Organization Address", Usage.O),
  ADMIN_OBX_25("Admin OBX-25", ProfileFieldType.FIELD, "OBX", "Performing Organization Medical Directory", Usage.O),
  ADMIN_OBX_64994_7("Admin OBX 64994-7", ProfileFieldType.FIELD, "OBX", "Patient Eligibility Category for Vaccine Funding Program", Usage.R),
  ADMIN_OBX_30963_3("Admin OBX 30963-3", ProfileFieldType.FIELD, "OBX", "Vaccine Funding Source", null),
  ADMIN_OBX_30945_0("Admin OBX 30945-0", ProfileFieldType.FIELD, "OBX", "Vaccination Contraindication/Precaution", null),
  ADMIN_OBX_59785_6("Admin OBX 59785-6", ProfileFieldType.FIELD, "OBX", "Indications to immunize", null),
  ADMIN_OBX_59784_9("Admin OBX 59784-9", ProfileFieldType.FIELD, "OBX", "Disease with presumed immunity", null),
  ADMIN_OBX_31044_1("Admin OBX 31044-1", ProfileFieldType.FIELD, "OBX", "Reaction", null),
  ADMIN_OBX_69764_9("Admin OBX 69764-9", ProfileFieldType.FIELD, "OBX", "VIS Document Type", Usage.RE),
  ADMIN_OBX_29768_9("Admin OBX 29768-9", ProfileFieldType.FIELD, "OBX", "VIS Version Date", Usage.RE),
  ADMIN_OBX_30956_7("Admin OBX 30956-7", ProfileFieldType.FIELD, "OBX", "VIS Vaccine Type", Usage.RE),
  ADMIN_OBX_29769_7("Admin OBX 29769-7", ProfileFieldType.FIELD, "OBX", "VIS Delivery Date", Usage.RE),
  ADMIN_NTE("Admin NTE", ProfileFieldType.SEGMENT, "NTE", "Note Segment", Usage.O),
  HIST_ORC("Hist ORC", ProfileFieldType.SEGMENT, "ORC", "Order Request Segment", Usage.R),
  HIST_ORC_1("Hist ORC-1", ProfileFieldType.FIELD, "ORC", "Order Control", Usage.R),
  HIST_ORC_2("Hist ORC-2", ProfileFieldType.FIELD, "ORC", "Placer Order Number", Usage.RE),
  HIST_ORC_3("Hist ORC-3", ProfileFieldType.FIELD, "ORC", "Filler Order Number", Usage.R),
  HIST_ORC_4("Hist ORC-4", ProfileFieldType.FIELD, "ORC", "Placer Group Number", Usage.O),
  HIST_ORC_5("Hist ORC-5", ProfileFieldType.FIELD, "ORC", "Order Status", Usage.O),
  HIST_ORC_6("Hist ORC-6", ProfileFieldType.FIELD, "ORC", "Response Flag", Usage.O),
  HIST_ORC_7("Hist ORC-7", ProfileFieldType.FIELD, "ORC", "Quantity/Timing", Usage.X),
  HIST_ORC_8("Hist ORC-8", ProfileFieldType.FIELD, "ORC", "Parent", Usage.O),
  HIST_ORC_9("Hist ORC-9", ProfileFieldType.FIELD, "ORC", "Date/Time of Transaction", Usage.O),
  HIST_ORC_10("Hist ORC-10", ProfileFieldType.FIELD, "ORC", "Entered By", Usage.RE),
  HIST_ORC_11("Hist ORC-11", ProfileFieldType.FIELD, "ORC", "Verified By", Usage.O),
  HIST_ORC_12("Hist ORC-12", ProfileFieldType.FIELD, "ORC", "Ordering Provider", Usage.RE),
  HIST_ORC_13("Hist ORC-13", ProfileFieldType.FIELD, "ORC", "Enterer's Location", Usage.O),
  HIST_ORC_14("Hist ORC-14", ProfileFieldType.FIELD, "ORC", "Call Back Phone Number", Usage.O),
  HIST_ORC_15("Hist ORC-15", ProfileFieldType.FIELD, "ORC", "Order Effective Date/Time", Usage.O),
  HIST_ORC_16("Hist ORC-16", ProfileFieldType.FIELD, "ORC", "Order Control Code Reason", Usage.O),
  HIST_ORC_17("Hist ORC-17", ProfileFieldType.FIELD, "ORC", "Entering Organization", Usage.RE),
  HIST_ORC_18("Hist ORC-18", ProfileFieldType.FIELD, "ORC", "Entering Device", Usage.O),
  HIST_ORC_19("Hist ORC-19", ProfileFieldType.FIELD, "ORC", "Action By", Usage.O),
  HIST_ORC_20("Hist ORC-20", ProfileFieldType.FIELD, "ORC", "Advanced Beneficiary Notice Code", Usage.O),
  HIST_ORC_21("Hist ORC-21", ProfileFieldType.FIELD, "ORC", "Ordering Facility Name", Usage.O),
  HIST_ORC_22("Hist ORC-22", ProfileFieldType.FIELD, "ORC", "Ordering Facility Address", Usage.O),
  HIST_ORC_23("Hist ORC-23", ProfileFieldType.FIELD, "ORC", "Ordering Facility Phone Number", Usage.O),
  HIST_ORC_24("Hist ORC-24", ProfileFieldType.FIELD, "ORC", "Order Provider Address", Usage.O),
  HIST_ORC_25("Hist ORC-25", ProfileFieldType.FIELD, "ORC", "Order Status Modifier", Usage.O),
  HIST_ORC_26("Hist ORC-26", ProfileFieldType.FIELD, "ORC", "Advanced Beneficiary Notice Override Reason", Usage.O),
  HIST_ORC_27("Hist ORC-27", ProfileFieldType.FIELD, "ORC", "Filler's Expected Availability Date/Time", Usage.O),
  HIST_ORC_28("Hist ORC-28", ProfileFieldType.FIELD, "ORC", "Confidentiality Code", Usage.O),
  HIST_ORC_29("Hist ORC-29", ProfileFieldType.FIELD, "ORC", "Order Type", Usage.O),
  HIST_ORC_30("Hist ORC-30", ProfileFieldType.FIELD, "ORC", "Enterer Authorization Mode", Usage.O),
  HIST_ORC_31("Hist ORC-31", ProfileFieldType.FIELD, "ORC", "Parent Universal Service Identifier", Usage.O),
  HIST_RXA("Hist RXA", ProfileFieldType.SEGMENT, "RXA", "Pharmacy Administration Segment - Historical", Usage.RE),
  HIST_RXA_1("Hist RXA-1", ProfileFieldType.FIELD, "RXA", "Give Sub-ID Counter", Usage.R),
  HIST_RXA_2("Hist RXA-2", ProfileFieldType.FIELD, "RXA", "Administration Sub-ID Counter", Usage.R),
  HIST_RXA_3("Hist RXA-3", ProfileFieldType.FIELD, "RXA", "Date/Time Start of Administration", Usage.R),
  HIST_RXA_4("Hist RXA-4", ProfileFieldType.FIELD, "RXA", "Date/Time End of Administration", Usage.RE),
  HIST_RXA_5("Hist RXA-5", ProfileFieldType.FIELD, "RXA", "Administration Code", Usage.R),
  HIST_RXA_6("Hist RXA-6", ProfileFieldType.FIELD, "RXA", "Administered Amount", Usage.R),
  HIST_RXA_7("Hist RXA-7", ProfileFieldType.FIELD, "RXA", "Administered Units", Usage.RE),
  HIST_RXA_9("Hist RXA-9", ProfileFieldType.FIELD, "RXA", "Administered Notes", Usage.R),
  HIST_RXA_10("Hist RXA-10", ProfileFieldType.FIELD, "RXA", "Administering Provider", Usage.O),
  HIST_RXA_10_1("Hist RXA-10.1", ProfileFieldType.FIELD_PART, "RXA", " - ID Number", Usage.RE),
  HIST_RXA_10_2("Hist RXA-10.2", ProfileFieldType.FIELD_PART, "RXA", " - Family Name", Usage.RE),
  HIST_RXA_10_3("Hist RXA-10.3", ProfileFieldType.FIELD_PART, "RXA", " - Given Name", Usage.RE),
  HIST_RXA_10_4("Hist RXA-10.4", ProfileFieldType.FIELD_PART, "RXA", " - Second and Further Given Names or Initials Therof", Usage.RE),
  HIST_RXA_11("Hist RXA-11", ProfileFieldType.FIELD, "RXA", "Administered-at Location", Usage.O),
  HIST_RXA_11_4("Hist RXA-11.4", ProfileFieldType.FIELD_PART, "RXA", " - Facility", Usage.R),
  HIST_RXA_15("Hist RXA-15", ProfileFieldType.FIELD, "RXA", "Substance Lot Number", Usage.O),
  HIST_RXA_16("Hist RXA-16", ProfileFieldType.FIELD, "RXA", "Substance Expiration Date", Usage.O),
  HIST_RXA_17("Hist RXA-17", ProfileFieldType.FIELD, "RXA", "Substance Lot Mfr Name", Usage.O),
  HIST_RXA_20("Hist RXA-20", ProfileFieldType.FIELD, "RXA", "Completion Status", Usage.RE),
  HIST_RXA_21("Hist RXA-21", ProfileFieldType.FIELD, "RXA", "Action Code", Usage.R),
  HIST_RXR("Hist RXR", ProfileFieldType.SEGMENT, "RXR", "Route of Administration Segment", null),
  HIST_RXR_1("Hist RXR-1", ProfileFieldType.FIELD, "RXR", "Route", null),
  HIST_RXR_2("Hist RXR-2", ProfileFieldType.FIELD, "RXR", "Administration Site", null),
  HIST_OBX("Hist OBX", ProfileFieldType.SEGMENT, "OBX", "Observation Segment", null),
  HIST_NTE("Hist NTE", ProfileFieldType.SEGMENT, "NTE", "Note Segment", null),
  REFUSAL_ORC("Refusal ORC", ProfileFieldType.SEGMENT, "ORC", "Order Request Segment", Usage.R),
  REFUSAL_ORC_1("Refusal ORC-1", ProfileFieldType.FIELD, "ORC", "Order Control", Usage.R),
  REFUSAL_ORC_2("Refusal ORC-2", ProfileFieldType.FIELD, "ORC", "Placer Order Number", Usage.RE),
  REFUSAL_ORC_3("Refusal ORC-3", ProfileFieldType.FIELD, "ORC", "Filler Order Number", Usage.R),
  REFUSAL_ORC_4("Refusal ORC-4", ProfileFieldType.FIELD, "ORC", "Placer Group Number", Usage.O),
  REFUSAL_ORC_5("Refusal ORC-5", ProfileFieldType.FIELD, "ORC", "Order Status", Usage.O),
  REFUSAL_ORC_6("Refusal ORC-6", ProfileFieldType.FIELD, "ORC", "Response Flag", Usage.O),
  REFUSAL_ORC_7("Refusal ORC-7", ProfileFieldType.FIELD, "ORC", "Quantity/Timing", Usage.X),
  REFUSAL_ORC_8("Refusal ORC-8", ProfileFieldType.FIELD, "ORC", "Parent", Usage.O),
  REFUSAL_ORC_9("Refusal ORC-9", ProfileFieldType.FIELD, "ORC", "Date/Time of Transaction", Usage.O),
  REFUSAL_ORC_10("Refusal ORC-10", ProfileFieldType.FIELD, "ORC", "Entered By", Usage.RE),
  REFUSAL_ORC_11("Refusal ORC-11", ProfileFieldType.FIELD, "ORC", "Verified By", Usage.O),
  REFUSAL_ORC_12("Refusal ORC-12", ProfileFieldType.FIELD, "ORC", "Ordering Provider", Usage.RE),
  REFUSAL_ORC_13("Refusal ORC-13", ProfileFieldType.FIELD, "ORC", "Enterer's Location", Usage.O),
  REFUSAL_ORC_14("Refusal ORC-14", ProfileFieldType.FIELD, "ORC", "Call Back Phone Number", Usage.O),
  REFUSAL_ORC_15("Refusal ORC-15", ProfileFieldType.FIELD, "ORC", "Order Effective Date/Time", Usage.O),
  REFUSAL_ORC_16("Refusal ORC-16", ProfileFieldType.FIELD, "ORC", "Order Control Code Reason", Usage.O),
  REFUSAL_ORC_17("Refusal ORC-17", ProfileFieldType.FIELD, "ORC", "Entering Organization", Usage.RE),
  REFUSAL_ORC_18("Refusal ORC-18", ProfileFieldType.FIELD, "ORC", "Entering Device", Usage.O),
  REFUSAL_ORC_19("Refusal ORC-19", ProfileFieldType.FIELD, "ORC", "Action By", Usage.O),
  REFUSAL_ORC_20("Refusal ORC-20", ProfileFieldType.FIELD, "ORC", "Advanced Beneficiary Notice Code", Usage.O),
  REFUSAL_ORC_21("Refusal ORC-21", ProfileFieldType.FIELD, "ORC", "Ordering Facility Name", Usage.O),
  REFUSAL_ORC_22("Refusal ORC-22", ProfileFieldType.FIELD, "ORC", "Ordering Facility Address", Usage.O),
  REFUSAL_ORC_23("Refusal ORC-23", ProfileFieldType.FIELD, "ORC", "Ordering Facility Phone Number", Usage.O),
  REFUSAL_ORC_24("Refusal ORC-24", ProfileFieldType.FIELD, "ORC", "Order Provider Address", Usage.O),
  REFUSAL_ORC_25("Refusal ORC-25", ProfileFieldType.FIELD, "ORC", "Order Status Modifier", Usage.O),
  REFUSAL_ORC_26("Refusal ORC-26", ProfileFieldType.FIELD, "ORC", "Advanced Beneficiary Notice Override Reason", Usage.O),
  REFUSAL_ORC_27("Refusal ORC-27", ProfileFieldType.FIELD, "ORC", "Filler's Expected Availability Date/Time", Usage.O),
  REFUSAL_ORC_28("Refusal ORC-28", ProfileFieldType.FIELD, "ORC", "Confidentiality Code", Usage.O),
  REFUSAL_ORC_29("Refusal ORC-29", ProfileFieldType.FIELD, "ORC", "Order Type", Usage.O),
  REFUSAL_ORC_30("Refusal ORC-30", ProfileFieldType.FIELD, "ORC", "Enterer Authorization Mode", Usage.O),
  REFUSAL_ORC_31("Refusal ORC-31", ProfileFieldType.FIELD, "ORC", "Parent Universal Service Identifier", Usage.O),
  REFUSAL_RXA("Refusal RXA", ProfileFieldType.SEGMENT, "RXA", "Pharmacy Administration Segment - Refusal", Usage.R),
  REFUSAL_RXA_1("Refusal RXA-1", ProfileFieldType.FIELD, "RXA", "Give Sub-ID Counter", Usage.R),
  REFUSAL_RXA_2("Refusal RXA-2", ProfileFieldType.FIELD, "RXA", "Administration Sub-ID Counter", Usage.R),
  REFUSAL_RXA_3("Refusal RXA-3", ProfileFieldType.FIELD, "RXA", "Date/Time Start of Administration", Usage.R),
  REFUSAL_RXA_4("Refusal RXA-4", ProfileFieldType.FIELD, "RXA", "Date/Time End of Administration", Usage.RE),
  REFUSAL_RXA_5("Refusal RXA-5", ProfileFieldType.FIELD, "RXA", "Administration Code", Usage.R),
  REFUSAL_RXA_6("Refusal RXA-6", ProfileFieldType.FIELD, "RXA", "Administered Amount", Usage.R),
  REFUSAL_RXA_7("Refusal RXA-7", ProfileFieldType.FIELD, "RXA", "Administered Units", Usage.O),
  REFUSAL_RXA_9("Refusal RXA-9", ProfileFieldType.FIELD, "RXA", "Administered Notes", Usage.O),
  REFUSAL_RXA_10("Refusal RXA-10", ProfileFieldType.FIELD, "RXA", "Administering Provider", Usage.O),
  REFUSAL_RXA_10_1("Refusal RXA-10.1", ProfileFieldType.FIELD_PART, "RXA", " - ID Number", Usage.RE),
  REFUSAL_RXA_10_2("Refusal RXA-10.2", ProfileFieldType.FIELD_PART, "RXA", " - Family Name", Usage.RE),
  REFUSAL_RXA_10_3("Refusal RXA-10.3", ProfileFieldType.FIELD_PART, "RXA", " - Given Name", Usage.RE),
  REFUSAL_RXA_10_4("Refusal RXA-10.4", ProfileFieldType.FIELD_PART, "RXA", " - Second and Further Given Names or Initials Therof", Usage.RE),
  REFUSAL_RXA_11("Refusal RXA-11", ProfileFieldType.FIELD, "RXA", "Administered-at Location", Usage.O),
  REFUSAL_RXA_11_4("Refusal RXA-11.4", ProfileFieldType.FIELD_PART, "RXA", " - Facility", Usage.R),
  REFUSAL_RXA_15("Refusal RXA-15", ProfileFieldType.FIELD, "RXA", "Substance Lot Number", Usage.O),
  REFUSAL_RXA_16("Refusal RXA-16", ProfileFieldType.FIELD, "RXA", "Substance Expiration Date", Usage.O),
  REFUSAL_RXA_17("Refusal RXA-17", ProfileFieldType.FIELD, "RXA", "Substance Lot Mfr Name", Usage.O),
  REFUSAL_RXA_18("Refusal RXA-18", ProfileFieldType.FIELD, "RXA", "Substance/Treatment Refusal Reason", Usage.R),
  REFUSAL_RXA_20("Refusal RXA-20", ProfileFieldType.FIELD, "RXA", "Completion Status", Usage.R),
  REFUSAL_RXA_21("Refusal RXA-21", ProfileFieldType.FIELD, "RXA", "Action Code", Usage.R),
  REFUSAL_RXR("Refusal RXR", ProfileFieldType.SEGMENT, "RXR", "Route of Administration Segment", null),
  REFUSAL_RXR_1("Refusal RXR-1", ProfileFieldType.FIELD, "RXR", "Route", null),
  REFUSAL_RXR_2("Refusal RXR-2", ProfileFieldType.FIELD, "RXR", "Administration Site", null),
  REFUSAL_OBX("Refusal OBX", ProfileFieldType.SEGMENT, "OBX", "Observation Segment", null),
  REFUSAL_NTE("Refusal NTE", ProfileFieldType.SEGMENT, "NTE", "Note Segment", null),
  NON_ADMIN_ORC("Non-Admin ORC", ProfileFieldType.SEGMENT, "ORC", "Order Request Segment", Usage.R),
  NON_ADMIN_ORC_1("Non-Admin ORC-1", ProfileFieldType.FIELD, "ORC", "Order Control", Usage.R),
  NON_ADMIN_ORC_2("Non-Admin ORC-2", ProfileFieldType.FIELD, "ORC", "Placer Order Number", Usage.RE),
  NON_ADMIN_ORC_3("Non-Admin ORC-3", ProfileFieldType.FIELD, "ORC", "Filler Order Number", Usage.R),
  NON_ADMIN_ORC_4("Non-Admin ORC-4", ProfileFieldType.FIELD, "ORC", "Placer Group Number", Usage.O),
  NON_ADMIN_ORC_5("Non-Admin ORC-5", ProfileFieldType.FIELD, "ORC", "Order Status", Usage.O),
  NON_ADMIN_ORC_6("Non-Admin ORC-6", ProfileFieldType.FIELD, "ORC", "Response Flag", Usage.O),
  NON_ADMIN_ORC_7("Non-Admin ORC-7", ProfileFieldType.FIELD, "ORC", "Quantity/Timing", Usage.X),
  NON_ADMIN_ORC_8("Non-Admin ORC-8", ProfileFieldType.FIELD, "ORC", "Parent", Usage.O),
  NON_ADMIN_ORC_9("Non-Admin ORC-9", ProfileFieldType.FIELD, "ORC", "Date/Time of Transaction", Usage.O),
  NON_ADMIN_ORC_10("Non-Admin ORC-10", ProfileFieldType.FIELD, "ORC", "Entered By", Usage.RE),
  NON_ADMIN_ORC_11("Non-Admin ORC-11", ProfileFieldType.FIELD, "ORC", "Verified By", Usage.O),
  NON_ADMIN_ORC_12("Non-Admin ORC-12", ProfileFieldType.FIELD, "ORC", "Ordering Provider", Usage.RE),
  NON_ADMIN_ORC_13("Non-Admin ORC-13", ProfileFieldType.FIELD, "ORC", "Enterer's Location", Usage.O),
  NON_ADMIN_ORC_14("Non-Admin ORC-14", ProfileFieldType.FIELD, "ORC", "Call Back Phone Number", Usage.O),
  NON_ADMIN_ORC_15("Non-Admin ORC-15", ProfileFieldType.FIELD, "ORC", "Order Effective Date/Time", Usage.O),
  NON_ADMIN_ORC_16("Non-Admin ORC-16", ProfileFieldType.FIELD, "ORC", "Order Control Code Reason", Usage.O),
  NON_ADMIN_ORC_17("Non-Admin ORC-17", ProfileFieldType.FIELD, "ORC", "Entering Organization", Usage.RE),
  NON_ADMIN_ORC_18("Non-Admin ORC-18", ProfileFieldType.FIELD, "ORC", "Entering Device", Usage.O),
  NON_ADMIN_ORC_19("Non-Admin ORC-19", ProfileFieldType.FIELD, "ORC", "Action By", Usage.O),
  NON_ADMIN_ORC_20("Non-Admin ORC-20", ProfileFieldType.FIELD, "ORC", "Advanced Beneficiary Notice Code", Usage.O),
  NON_ADMIN_ORC_21("Non-Admin ORC-21", ProfileFieldType.FIELD, "ORC", "Ordering Facility Name", Usage.O),
  NON_ADMIN_ORC_22("Non-Admin ORC-22", ProfileFieldType.FIELD, "ORC", "Ordering Facility Address", Usage.O),
  NON_ADMIN_ORC_23("Non-Admin ORC-23", ProfileFieldType.FIELD, "ORC", "Ordering Facility Phone Number", Usage.O),
  NON_ADMIN_ORC_24("Non-Admin ORC-24", ProfileFieldType.FIELD, "ORC", "Order Provider Address", Usage.O),
  NON_ADMIN_ORC_25("Non-Admin ORC-25", ProfileFieldType.FIELD, "ORC", "Order Status Modifier", Usage.O),
  NON_ADMIN_ORC_26("Non-Admin ORC-26", ProfileFieldType.FIELD, "ORC", "Advanced Beneficiary Notice Override Reason", Usage.O),
  NON_ADMIN_ORC_27("Non-Admin ORC-27", ProfileFieldType.FIELD, "ORC", "Filler's Expected Availability Date/Time", Usage.O),
  NON_ADMIN_ORC_28("Non-Admin ORC-28", ProfileFieldType.FIELD, "ORC", "Confidentiality Code", Usage.O),
  NON_ADMIN_ORC_29("Non-Admin ORC-29", ProfileFieldType.FIELD, "ORC", "Order Type", Usage.O),
  NON_ADMIN_ORC_30("Non-Admin ORC-30", ProfileFieldType.FIELD, "ORC", "Enterer Authorization Mode", Usage.O),
  NON_ADMIN_ORC_31("Non-Admin ORC-31", ProfileFieldType.FIELD, "ORC", "Parent Universal Service Identifier", Usage.O),
  NON_ADMIN_RXA("Non-Admin RXA", ProfileFieldType.SEGMENT, "RXA", "Pharmacy Administration Segment - Non-Admin", Usage.R),
  NON_ADMIN_RXA_1("Non-Admin RXA-1", ProfileFieldType.FIELD, "RXA", "Give Sub-ID Counter", Usage.R),
  NON_ADMIN_RXA_2("Non-Admin RXA-2", ProfileFieldType.FIELD, "RXA", "Administration Sub-ID Counter", Usage.R),
  NON_ADMIN_RXA_3("Non-Admin RXA-3", ProfileFieldType.FIELD, "RXA", "Date/Time Start of Administration", Usage.R),
  NON_ADMIN_RXA_4("Non-Admin RXA-4", ProfileFieldType.FIELD, "RXA", "Date/Time End of Administration", Usage.RE),
  NON_ADMIN_RXA_5("Non-Admin RXA-5", ProfileFieldType.FIELD, "RXA", "Administration Code", Usage.R),
  NON_ADMIN_RXA_6("Non-Admin RXA-6", ProfileFieldType.FIELD, "RXA", "Administered Amount", Usage.RE),
  NON_ADMIN_RXA_7("Non-Admin RXA-7", ProfileFieldType.FIELD, "RXA", "Administered Units", Usage.O),
  NON_ADMIN_RXA_9("Non-Admin RXA-9", ProfileFieldType.FIELD, "RXA", "Administered Notes", Usage.O),
  NON_ADMIN_RXA_10("Non-Admin RXA-10", ProfileFieldType.FIELD, "RXA", "Administering Provider", Usage.O),
  NON_ADMIN_RXA_10_1("Non-Admin RXA-10.1", ProfileFieldType.FIELD_PART, "RXA", " - ID Number", Usage.RE),
  NON_ADMIN_RXA_10_2("Non-Admin RXA-10.2", ProfileFieldType.FIELD_PART, "RXA", " - Family Name", Usage.RE),
  NON_ADMIN_RXA_10_3("Non-Admin RXA-10.3", ProfileFieldType.FIELD_PART, "RXA", " - Given Name", Usage.RE),
  NON_ADMIN_RXA_10_4("Non-Admin RXA-10.4", ProfileFieldType.FIELD_PART, "RXA", " - Second and Further Given Names or Initials Therof", Usage.RE),
  NON_ADMIN_RXA_11("Non-Admin RXA-11", ProfileFieldType.FIELD, "RXA", "Administered-at Location", Usage.O),
  NON_ADMIN_RXA_11_4("Non-Admin RXA-11.4", ProfileFieldType.FIELD_PART, "RXA", " - Facility", Usage.R),
  NON_ADMIN_RXA_15("Non-Admin RXA-15", ProfileFieldType.FIELD, "RXA", "Substance Lot Number", Usage.O),
  NON_ADMIN_RXA_16("Non-Admin RXA-16", ProfileFieldType.FIELD, "RXA", "Substance Expiration Date", Usage.O),
  NON_ADMIN_RXA_17("Non-Admin RXA-17", ProfileFieldType.FIELD, "RXA", "Substance Lot Mfr Name", Usage.O),
  NON_ADMIN_RXA_20("Non-Admin RXA-20", ProfileFieldType.FIELD, "RXA", "Completion Status", Usage.RE),
  NON_ADMIN_RXA_21("Non-Admin RXA-21", ProfileFieldType.FIELD, "RXA", "Action Code", Usage.R),
  NON_ADMIN_RXR("Non-Admin RXR", ProfileFieldType.SEGMENT, "RXR", "Route of Administration Segment", null),
  NON_ADMIN_RXR_1("Non-Admin RXR-1", ProfileFieldType.FIELD, "RXR", "Route", null),
  NON_ADMIN_RXR_2("Non-Admin RXR-2", ProfileFieldType.FIELD, "RXR", "Administration Site", null),
  NON_ADMIN_OBX("Non-Admin OBX", ProfileFieldType.SEGMENT, "OBX", "Observation Segment", null),
  NON_ADMIN_NTE("Non-Admin NTE", ProfileFieldType.FIELD, "NTE", "Note Segment", null),
  ;
  private String fieldName = "";
  private ProfileFieldType type = null;
  private String segmentName = "";
  private String description = "";
  private Usage cdcUsage = null;

  public Usage getCdcUsage() {
    return cdcUsage;
  }

  public void setCdcUsage(Usage cdcUsage) {
    this.cdcUsage = cdcUsage;
  }

  public String getFieldName() {
    return fieldName;
  }

  public ProfileFieldType getType() {
    return type;
  }

  public String getSegmentName() {
    return segmentName;
  }

  public String getDescription() {
    return description;
  }

  private ProfileField(String fieldName, ProfileFieldType type, String segmentName, String description) {
    this.fieldName = fieldName;
    this.type = type;
    this.segmentName = segmentName;
    this.description = description;
  }

  private ProfileField(String fieldName, ProfileFieldType type, String segmentName, String description, Usage cdcUsage) {
    this.fieldName = fieldName;
    this.type = type;
    this.segmentName = segmentName;
    this.description = description;
    this.cdcUsage = cdcUsage;
  }

}
